zoo = ('python', 'elephant', 'penguin', 'giraffe')
print('Number of animals in the zoo is', len(zoo))

new_zoo = ('monkey', 'camel', zoo)
print(new_zoo)
print('Number of cages in the new zoo is', len(new_zoo))
print('Animals brought from old zoo are', new_zoo[2])
print('The last animal brouht from the old zoo is', new_zoo[2][3])
print('Here is the new zoo again', new_zoo)
print('Number of animals in the new new zoo is', len(new_zoo)-1+len(new_zoo[2]))
